#!/bin/bash


function allowLastDockerIPv6 {
 ip -6 neigh add proxy $(docker inspect --format='{{.NetworkSettings.GlobalIPv6Address}}' $(docker ps -l -q)) dev eth1
 return $?
}

echo "Stop active docker."
docker stop $(docker ps -a -q) 2>/dev/null
echo "Remove stopped docker"
docker rm $(docker ps -a -q) 2>/dev/null

sleep 3

echo "start Selenium Stadalone"
docker run -d -p 4444:4444 ondrejp/selenium-standalone-firefox \
 && allowLastDockerIPv6

echo "start Selenium Stadalone Debug"
docker run -d -p 4466:4444 -p 5931:5900 ondrejp/selenium-standalone-firefox-debug \
 && allowLastDockerIPv6


echo "start Selenium hub/nodes"
docker run -d -p 4488:4444 --name selenium-hub ondrejp/selenium-hub

export NodeRun="docker run -d --link selenium-hub:hub ondrejp/selenium-node-"

for I in {1..16}; do

 ${NodeRun}firefox \
  && allowLastDockerIPv6

 ${NodeRun}chrome \
  && allowLastDockerIPv6

done   


for I in {1..4} ; do 

 ${NodeRun}firefox:24 \
  && allowLastDockerIPv6
  
 ${NodeRun}firefox:30 \
  && allowLastDockerIPv6
  
 ${NodeRun}firefox:beta \
  && allowLastDockerIPv6
  
 ${NodeRun}chrome:beta \
  && allowLastDockerIPv6
  
done


echo "start Selenium hub/nodes Debug"
docker run -d -p 4499:4444 --name selenium-hub-debug ondrejp/selenium-hub


echo "Start selenium firefox debug vnc:5933"
docker run -d \
 -p 5933:5900 \
 --link selenium-hub-debug:hub ondrejp/selenium-node-firefox-debug \
  && allowLastDockerIPv6
  

echo "Start selenium chrome debug vnc:5934"
docker run -d \
 -p 5934:5900 \
 --link selenium-hub-debug:hub ondrejp/selenium-node-chrome-debug \
  && allowLastDockerIPv6
  
